import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { EB_Garamond } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const garamond = EB_Garamond({
  variable: '--font-garamond',
  weight: [ '400', '500', '600', '700', '800', ],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${garamond.variable} font-serif`}
      >
        {children}
      </body>
    </html>
  );
}
